/*
Copyright 2026 Keiailab.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package resources

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"

	cachev1alpha1 "github.com/keiailab/valkey-operator/api/v1alpha1"
)

// CertificateGVK — cert-manager.io/v1 Certificate.
//
// 본 패키지는 cert-manager 의존성을 추가하지 않고 unstructured 로 다룬다 — CRD 미설치
// 시 NoMatchError 가 자연스럽게 fail-soft.
var CertificateGVK = schema.GroupVersionKind{
	Group:   "cert-manager.io",
	Version: "v1",
	Kind:    "Certificate",
}

// IssuerGVK — cert-manager.io/v1 Issuer (namespace-scope).
// AutoSelfSigned 옵션에서 operator 가 자동 생성.
var IssuerGVK = schema.GroupVersionKind{
	Group:   "cert-manager.io",
	Version: "v1",
	Kind:    "Issuer",
}

// IssuerKind 표준 식별자 — cert-manager 의 IssuerRef.Kind 기본값.
const IssuerKindClusterIssuer = "ClusterIssuer"

// IssuerKindIssuer — namespace-scope Issuer (AutoSelfSigned 시 사용).
const IssuerKindIssuer = "Issuer"

// CertificateSecretName — cert-manager 가 만들 Secret 이름.
func CertificateSecretName(crName string) string { return crName + "-tls" }

// CertificateName — Certificate CR 이름.
func CertificateName(crName string) string { return crName + "-tls" }

// SelfSignedIssuerName — AutoSelfSigned 시 자동 생성하는 Issuer 이름.
func SelfSignedIssuerName(crName string) string { return crName + "-selfsigned" }

// BuildSelfSignedIssuer — Spec.TLS.CertManager.AutoSelfSigned=true 일 때 namespace
// 에 자동 생성하는 cert-manager Issuer (kind=Issuer, spec.selfSigned: {}).
//
// 외부 chart 의 `tls.autoGenerated` 패턴과 동등 — 사용자가 cert-manager 만
// 설치해두면 IssuerRef 명시 없이 *operator-issued root* 로 TLS 활성.
// CRD 미설치 시 unstructured apply 가 NoMatchError fail-soft (ADR-0010 패턴).
func BuildSelfSignedIssuer(crName, namespace string) *unstructured.Unstructured {
	u := &unstructured.Unstructured{}
	u.SetGroupVersionKind(IssuerGVK)
	u.SetName(SelfSignedIssuerName(crName))
	u.SetNamespace(namespace)
	u.SetLabels(CommonLabels(crName, "valkey"))
	u.Object["spec"] = map[string]any{
		"selfSigned": map[string]any{},
	}
	return u
}

// BuildCertificateForValkey — Valkey 단일 인스턴스 / replication 토폴로지용 Certificate.
// 미활성 (TLS nil / Enabled=false / CertManager.IssuerRef 누락) 시 nil 반환.
func BuildCertificateForValkey(v *cachev1alpha1.Valkey) *unstructured.Unstructured {
	if v.Spec.TLS == nil || !v.Spec.TLS.Enabled || v.Spec.TLS.CertManager == nil {
		return nil
	}
	cm := v.Spec.TLS.CertManager
	issuerName, issuerKind := resolveIssuer(v.Name, cm)
	if issuerName == "" {
		return nil
	}

	dnsNames := []any{
		ClientServiceName(v.Name) + "." + v.Namespace + ".svc",
		ClientServiceName(v.Name) + "." + v.Namespace + ".svc.cluster.local",
		HeadlessServiceName(v.Name) + "." + v.Namespace + ".svc",
		"*." + HeadlessServiceName(v.Name) + "." + v.Namespace + ".svc",
	}

	spec := map[string]any{
		"secretName": CertificateSecretName(v.Name),
		"commonName": ClientServiceName(v.Name) + "." + v.Namespace + ".svc",
		"dnsNames":   dnsNames,
		"issuerRef": map[string]any{
			"name": issuerName,
			"kind": issuerKind,
		},
		"usages": []any{"server auth", "client auth"},
	}
	if cm.Duration != "" {
		spec["duration"] = cm.Duration
	}
	if cm.RenewBefore != "" {
		spec["renewBefore"] = cm.RenewBefore
	}

	u := &unstructured.Unstructured{}
	u.SetGroupVersionKind(CertificateGVK)
	u.SetName(CertificateName(v.Name))
	u.SetNamespace(v.Namespace)
	u.SetLabels(CommonLabels(v.Name, "valkey"))
	u.Object["spec"] = spec
	return u
}

// resolveIssuer — Spec.TLS.CertManager 에서 사용할 issuer name + kind 결정.
// AutoSelfSigned=true 시 operator 가 자동 생성한 namespace-scope Issuer 를 사용.
// 그 외엔 사용자 명시 IssuerRef 사용. 둘 다 비어있으면 ("", "") 반환 → 호출자가 nil.
func resolveIssuer(crName string, cm *cachev1alpha1.CertManagerSpec) (name, kind string) {
	if cm.AutoSelfSigned {
		return SelfSignedIssuerName(crName), IssuerKindIssuer
	}
	if cm.IssuerRef.Name == "" {
		return "", ""
	}
	if cm.IssuerRef.Kind != "" {
		return cm.IssuerRef.Name, cm.IssuerRef.Kind
	}
	return cm.IssuerRef.Name, IssuerKindClusterIssuer
}

// BuildCertificateForCluster — cert-manager Certificate CR. 미활성 시 nil.
//
// commonName / dnsNames 는 valkey 노드의 DNS 표면을 모두 커버:
//   - <crName>.<namespace>.svc / <crName>.<namespace>.svc.cluster.local (client Service)
//   - <crName>-headless.<namespace>.svc (headless Service)
//   - *.<crName>-headless.<namespace>.svc (StatefulSet pod)
//
// duration / renewBefore 는 Spec.TLS.CertManager 의 값을 사용하며, 미명시 시 cert-manager
// 기본값 (90d / 30d) 위임.
func BuildCertificateForCluster(vc *cachev1alpha1.ValkeyCluster) *unstructured.Unstructured {
	if vc.Spec.TLS == nil || !vc.Spec.TLS.Enabled || vc.Spec.TLS.CertManager == nil {
		return nil
	}
	cm := vc.Spec.TLS.CertManager
	issuerName, issuerKind := resolveIssuer(vc.Name, cm)
	if issuerName == "" {
		return nil
	}

	dnsNames := []any{
		ClientServiceName(vc.Name) + "." + vc.Namespace + ".svc",
		ClientServiceName(vc.Name) + "." + vc.Namespace + ".svc.cluster.local",
		HeadlessServiceName(vc.Name) + "." + vc.Namespace + ".svc",
		"*." + HeadlessServiceName(vc.Name) + "." + vc.Namespace + ".svc",
	}

	spec := map[string]any{
		"secretName": CertificateSecretName(vc.Name),
		"commonName": ClientServiceName(vc.Name) + "." + vc.Namespace + ".svc",
		"dnsNames":   dnsNames,
		"issuerRef": map[string]any{
			"name": issuerName,
			"kind": issuerKind,
		},
		"usages": []any{"server auth", "client auth"},
	}
	if cm.Duration != "" {
		spec["duration"] = cm.Duration
	}
	if cm.RenewBefore != "" {
		spec["renewBefore"] = cm.RenewBefore
	}

	u := &unstructured.Unstructured{}
	u.SetGroupVersionKind(CertificateGVK)
	u.SetName(CertificateName(vc.Name))
	u.SetNamespace(vc.Namespace)
	u.SetLabels(CommonLabels(vc.Name, "valkey-cluster"))
	u.Object["spec"] = spec
	return u
}
