{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.auth.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.auth.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey-operator.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreKind }}
    name: {{ .Values.externalSecrets.secretStoreName }}
  target:
    name: {{ .Values.externalSecrets.auth.targetName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.auth.passwordKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.auth.remoteKey | quote }}
{{- end }}
{{ if and .Values.externalSecrets.enabled .Values.externalSecrets.backupTarget.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.backupTarget.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey-operator.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreKind }}
    name: {{ .Values.externalSecrets.secretStoreName }}
  target:
    name: {{ .Values.externalSecrets.backupTarget.targetName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.backupTarget.accessKeyIdKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.backupTarget.accessKeyIdRemoteKey | quote }}
    - secretKey: {{ .Values.externalSecrets.backupTarget.secretAccessKeyKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.backupTarget.secretAccessKeyRemoteKey | quote }}
{{- end }}
