{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.auth.enabled }}
{{ include "keiailab.secrets.externalSecret" (dict
    "ctx" .
    "name" .Values.externalSecrets.auth.name
    "labels" (include "valkey-operator.labels" .)
    "refreshInterval" .Values.externalSecrets.refreshInterval
    "secretStoreKind" .Values.externalSecrets.secretStoreKind
    "secretStoreName" .Values.externalSecrets.secretStoreName
    "targetName" .Values.externalSecrets.auth.targetName
    "data" (list
      (dict "secretKey" .Values.externalSecrets.auth.passwordKey "remoteKey" .Values.externalSecrets.auth.remoteKey))) }}
{{- end }}
{{ if and .Values.externalSecrets.enabled .Values.externalSecrets.backupTarget.enabled }}
---
{{ include "keiailab.secrets.externalSecret" (dict
    "ctx" .
    "name" .Values.externalSecrets.backupTarget.name
    "labels" (include "valkey-operator.labels" .)
    "refreshInterval" .Values.externalSecrets.refreshInterval
    "secretStoreKind" .Values.externalSecrets.secretStoreKind
    "secretStoreName" .Values.externalSecrets.secretStoreName
    "targetName" .Values.externalSecrets.backupTarget.targetName
    "data" (list
      (dict "secretKey" .Values.externalSecrets.backupTarget.accessKeyIdKey "remoteKey" .Values.externalSecrets.backupTarget.accessKeyIdRemoteKey)
      (dict "secretKey" .Values.externalSecrets.backupTarget.secretAccessKeyKey "remoteKey" .Values.externalSecrets.backupTarget.secretAccessKeyRemoteKey))) }}
{{- end }}
