{{- if .Values.serviceAccount.create -}}
{{ include "keiailab.rbac.serviceAccount" (dict
    "ctx" .
    "name" (include "valkey-operator.serviceAccountName" .)
    "labels" (include "valkey-operator.labels" .)
    "annotations" .Values.serviceAccount.annotations
    "automountToken" true) }}
{{- end }}
