# Artifact Hub repository metadata for keiailab/valkey-operator
# https://artifacthub.io/docs/topics/repositories/
#
# ArtifactHub 등록 완료 (2026-05-06):
#   name: keiailab-valkey-operator (다른 vendor 의 'valkey-operator' 와 충돌 회피)
#   URL:  https://keiailab.github.io/valkey-operator
#   path: https://artifacthub.io/packages/helm/keiailab-valkey-operator/valkey-operator
#
# signingKey 는 keiailab 공통 PGP key 재사용.

repositoryID: 16085dd0-0f19-4c6b-ab90-bd97105bdf42

signingKey:
  fingerprint: "F1A6893583E632A757FF6767F3CC8C6AEC9CEB08"
  armored: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    mQINBGopEOUBEACwlJ6UHpLsAMbSx+WRagM9CcQJzSV3G3xCSZvAvY2+RE1BHcqq
    X4n3ESyUBhtoIJ//Mdz/enWR+7NSLsKrjtxgkE9USbb6zT/zbnWtpW/S7meZxexw
    bmYY3usBjy+o1dfgiAyxukKoHoTkC4RNsvMKTSM1WB1XssqC1o+/AVvE82HbYNjV
    Up80eg8oBj0nW4Qk+gkL5jgmpfndEc+qBHb1+I0pVHIVhcXVmrBBPC60zeI8pMXW
    BA+Fct8B8K0VmFdUMwf1mfNy4i7tuLbGZRVQJ8dTP3O7EWJjLRgVscr5+B/gsynE
    N9z0idNhsmK3haP9TIxyVJeNZ6rNg+Wh2/tRiZitbgqGxxY5nkXltX7c8QPtpi0j
    y8y1tAgacDvg8fnXsK1GH49+5qYfvvRxgnM0gCZeMtOn/nV+RTieEmj2FMZwjPeE
    c95C+9a9hS0hNgql5cN/wS8OBbsGtrNixzavsWn25surZz8MRoWsTajh9cZwGQ7t
    4aCC/xrRSmwN52IYE+wze5BkqPzbfFv78uxh2o/MGGaF7xHLCPc8uhTvCzSVIrh0
    SJje0gaCpROlLmE7RlMGu+mEJJCvHeXaIrG9vtoT3b3BtRRJTZ0drPTzi1MUh19T
    WTlDv2Ctg90EEKqKC6XOZDA+IELPay0t0vL9O8L2GbKtrT7TWtXB8oZquQARAQAB
    tCNLZWlhaWxhYiBIZWxtIDxoZWxtQGtlaWFpbGFiLmxvY2FsPokCcwQTAQgAXRYh
    BPGmiTWD5jKnV/9nZ/PMjGrsnOsIBQJqKRDlGxSAAAAAAAQADm1hbnUyLDIuNSsx
    LjEyLDAsMwIbAwUJA8JnAAULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRDz
    zIxq7JzrCJpXD/94vO3w0BQI14jX8ljuwExqugr46y4qokp8H8V5Rbrq7C1/UTGm
    0gYRwokogjoV4dVhwEP9MgdNYi4KQWTFjFZmmBqPrjBAO9djmxWt+efQIED4E4Im
    oyZO/wxfTc4UtAdGEUzb53OV2/pFMTsFSETpC8hVVY8X6LqJA5gcxRiGbbp7QDvS
    XOXNC4aScYT5xoig1ohcED74CSBIQr8qpqgbjHUJJdLfSHFgyKfuyxJjtCCwNyp+
    MV8qmZuYpsxWhPSvDlbjB7kaZwnNWzQQXBGwY81CtUGLJzPyUJ6yrbI7E6w4F76E
    93n0vTe2TnAbjgNw2CcrcNUk7bnC5OFPrg3z+G5opx/ecw4JzkrPip2j8cDzzxGO
    QHsJWEzAwNRpfEAJYSjDoWfie8Wox+hZDa5WNSYHeIJ3f+jYieQmW3uWF0ZfMSvV
    pY4i91BLrIbWjNK55Rx7lCd7RTGVx9evcMyLEEg8XiHJyUHBliitlYMz1lka8m6/
    hLS0bPJnYfRN3P659bouGI+HxyudpfzCIlXzq+uott8R6mwEaWWmzcG98JwwresW
    O2OGiPNZi1aBTs0NofebGJwdVu2aPTJhkWtwG6pxEzpFOB0H7coy2pQLSN8CJIm6
    7swYBI2OzpGy1NbLswI0rqBT6FnBxIwwDWAQe3HIcYtFqTY3FOW9zSw5Vg==
    =dQlA
    -----END PGP PUBLIC KEY BLOCK-----

owners:
  - name: eightynine01
    email: support@keiailab.com
